### ISSUE TITLE
diff off by factor of 100

### ISSUE THREAD

**Issue by mooleshacat** [sugarchain-project/explorer#11]
![image](https://user-images.githubusercontent.com/43627985/64497961-eff4fb00-d27f-11e9-9f4e-8fa156643c93.png)
diff off by factor of 100

- we need an offset variable for the difficulty
- we need a setting for number of decimal digits to show

also not sure why in the config we have to specify hashrate is GH or MH or KH etc. shouldn't it grab the hashrate from the wallet daemon, and then convert it into human readable format?

https://pexa.easyxpool.tk/ (sample installation)

Thanks... I really like the explorer :+1:

**Comment by cryptozeny** [comment]
its converting automatically the net_hash to human readable format.

**Comment by mooleshacat** [comment]
> its converting automatically the net_hash to human readable format.

**Yes that is what it needs -** it needs to convert hashrates + difficulties to human readable format automatically

**Difficulty is off by factor of 100 -** in the image above it should be 155.682 not 1.55682

**If it automatically does this already, then it is broken and needs to be fixed. Hence the bug report.**

If it automatically does this already, please remove the last few configuration lines where it asks if it is GH MH KH etc. because it is pointless and confusing to leave it in

**Comment by cryptozeny** [comment]
> Difficulty is off by factor of 100 - in the image above it should be 155.682 not 1.55682

no its already correct. plz check `getdifficulty` or `getmininginfo`

![image](https://user-images.githubusercontent.com/37016180/64560827-43507180-d384-11e9-86ee-60f901a1cffc.png)

![image](https://user-images.githubusercontent.com/37016180/64560844-4c414300-d384-11e9-9ab8-33ac8757e8e0.png)

![image](https://user-images.githubusercontent.com/37016180/64560866-55caab00-d384-11e9-8f47-2d20f632d432.png)

i assume you may something confused about `scientific notation`? plz check it.

https://www.mathsisfun.com/numbers/scientific-notation.html

**Comment by cryptozeny** [comment]
in your screenshot difficulty at the end `+2` means `*100`

**Comment by cryptozeny** [comment]
i think this is already resolved. closing.
